<?php
session_start(); // Start the session

$readonlyAttribute = "";

if (isset($_SESSION["autogeneratedUsername"])) {
    $autogeneratedUsername = $_SESSION["autogeneratedUsername"];
    $readonlyAttribute = "readonly";
}

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Retrieve form data
    $username = $_POST["username"];
    $password = $_POST["password"];

    // Establish a database connection (replace with your database credentials)
        $servername = "localhost"; 
        $hostname = "root"; 
        $password = ""; 
        $dbname = "graduation"; 

        $conn = new mysqli($servername, $hostname, $password, $dbname);

        if ($conn->connect_error) {
            die("Connection failed: " . $conn->connect_error);
        }

    // Prepare a SQL statement to retrieve user data by username
    $sql = "SELECT * FROM register WHERE username = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("s", $username);

    if ($stmt->execute()) {
        $result = $stmt->get_result();

        if ($result->num_rows == 1) {
            $row = $result->fetch_assoc();
            $stored_password = $row["password"];
            $user_role = $row["role"];

            // Verify the hashed password
            if (password_verify($password, $stored_password)) {
                // Password is correct - login successful
                $_SESSION["username"] = $username;
                $_SESSION["role"] = $user_role;

                // Redirect based on user role
                if ($user_role == "registrar") {
                    header("Location: registrar_dashboard.php");
                } elseif ($user_role == "dean") {
                    header("Location: dean_dashboard.php");
                } elseif ($user_role == "hod") {
                    header("Location: hod_dashboard.php");
                } elseif ($user_role == "student") {
                    header("Location: student_dashboard.php");
                } else {
                    // Handle other roles or errors here
                }
            } else {
                // Invalid password
                $error_message = "Invalid password";
            }
        } else {
            // User not found
            $error_message = "User not found";
        }
    } else {
        // Error executing the query
        echo "Error: " . $sql . "<br>" . $conn->error;
    }

    // Close the database connection
    $stmt->close();
    $conn->close();
}
?>

<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" href="./assets/css/images/bara-logo-a2.png" type="image/x-icon">
    <title>Graduation and Exam Application</title>
    <link rel="stylesheet" type="text/css" href="./assets/css/css/index.css">
</head>
<body>
    <div class="header">
        <img src="./assets/css/images/bara-logo-a.png" alt="Logo" class="logo.lg">
        <h1 class="header-text">GRADUATION AND EXAMINATION APPLICATION SYSTEM</h1>
    </div>
    <div class="container">
        <h2>Login</h2>

        <?php if (!empty($error_message)): ?>
        <p style="color: red;"><?php echo $error_message; ?></p>
        <?php endif; ?>

        <form id="loginForm" action=" " method="post" onsubmit="return validateForm()">
    
        <div class="input-container">
            <label for="username">UserID:<span>*</span></label>
            <?php if (isset($_SESSION["redirectedFromRegistration"]) && $_SESSION["redirectedFromRegistration"]): ?>

            <!-- Display the autogenerated username as readonly if redirected from registration -->
            <input type="text" name="username" id="username" value="<?php echo $autogeneratedUsername; ?>" readonly required>
            <?php else: ?>

            <!-- Display a blank, editable username if not redirected from registration -->
            <input type="text" name="username" id="username" value="<?php echo isset($username) ? $username : ''; ?>" required>
            <?php endif; ?>
        </div>

            <div class="input-container">
                <label for="password">Password:<span>*</span></label>
                <input type="password" name="password" id="password" required>
            </div>
            <button type="submit">Login</button>
        </form>

        <a href="reset.html" class="password">Forgot password</a>
        <a href="register.php">Register here</a>
    </div>
    <script>
        function validateForm() {
        var username = document.getElementById("username").value;
        var password = document.getElementById("password").value;

        if (username === "" || password === "") {
            alert("Please enter both username and password.");
            return false; // Prevent form submission
        }

        return true; // Allow form submission
        }
        var redirectedFromRegistration = <?php echo json_encode($redirectedFromRegistration); ?>;
        var usernameInput = document.getElementById("username");

        if (!redirectedFromRegistration) {
            usernameInput.removeAttribute("readonly");
        }
        <?php unset($_SESSION["redirectedFromRegistration"]); ?>
    </script>
        <img class="logo.sm" src="./assets/css/images/bara-logo-a2.png" alt="Logo for smaller screens" style="display: none;">

        <!-- Logo for screens larger than 768px -->
        <img class="logo.lg" src="./assets/css/images/bara-logo-a.png" alt="Logo for larger screens" style="display: none;">
</body>
</html>
